[theme]
base="light"
# main page background
backgroundColor = "#FFFFFF"        # pure white
# accent (buttons, sliders, highlights)
primaryColor      = "#FFFACD"      # “lemon chiffon” – a soft pale lemon
# secondary panels (sidebar, cards, etc.)
secondaryBackgroundColor = "#FFFACD"
# text remains dark for contrast
textColor         = "#000000"
