[theme]
# Inherit from the light base theme
base = "light"
# Set primary (accent) color to your lemon‑green
primaryColor = "#6bcc2f"
# (Optional) Keep the rest of your palette consistent
backgroundColor        = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor              = "#000000"
